
const PDFDocument = require('pdfkit'); 
const ExcelJS = require('exceljs'); 
const Wallet = require('../model/walletModel');
const order = require('../model/orderModel');

const loadSalesReport = async (req, res) => {
    try {
        const { startDate, endDate } = req.query;

        let query = { 'products.orderStatus': 'Delivered' };

        if (startDate && endDate) {
            const start = new Date(startDate);
            const end = new Date(endDate);
           
            end.setHours(23, 59, 59, 999);

            query.orderDate = {
                $gte: start,
                $lte: end
            };
        }

        let SalesReport = await order.aggregate([
            {
                $lookup: {
                  from: "addresses", 
                  localField: 'addressId',
                  foreignField: '_id',
                  as: 'address' 
                }
              },
              { $unwind: '$address' },
            { $unwind: '$products' },
            {
                $lookup: {
                    from: "products",
                    localField: 'products.productId',
                    foreignField: '_id',
                    as: 'product'
                }
            },
            { $unwind: '$product' },
            { $match: query },
            { $sort: { 'orderDate': -1 } },
            {
                $project: {
                    _id: 1,
                    orderDate: 1,
                    'product.productname': 1,
                    'products.productquantity': 1,
                    'user.name': 1,
                    totalAmount: 1,
                    discountAmount: 1,
                    selectedPaymentMethod: 1  
                }
            }
        ]);

       
     
        let totalSale = SalesReport.length;
        res.render('admin/SalesReport', { SalesReport, totalSale });
    } catch (error) {
        console.error("Error loading sales report:", error);
        res.status(500).send('Server error');
    }
};

  
  
// downloadPdf
const downloadPdf = async (req, res) => {
    try {
        const { startDate, endDate } = req.query;

        let query = { 'products.orderStatus': 'Delivered' };

        if (startDate && endDate) {
            const start = new Date(startDate);
            const end = new Date(endDate);
            end.setHours(23, 59, 59, 999);

            query.orderDate = {
                $gte: start,
                $lte: end
            };
        }

        let SalesReport = await order.aggregate([
            {
                $lookup: {
                  from: "addresses", 
                  localField: 'addressId',
                  foreignField: '_id',
                  as: 'address' 
                }
              },
              { $unwind: '$address' },
            { $unwind: '$products' },
            {
                $lookup: {
                    from: "products",
                    localField: 'products.productId',
                    foreignField: '_id',
                    as: 'product'
                }
            },
            { $unwind: '$product' },
            { $match: query },
            { $sort: { 'orderDate': -1 } },
            {
                $project: {
                    _id: 1,
                    orderDate: 1,
                    'product.productname': 1,
                    'products.productquantity': 1,
                    'user.name': 1,
                    totalAmount: 1,
                    discountAmount: 1,
                    selectedPaymentMethod: 1  
                }
            }
        ]);

        const doc = new PDFDocument({ margin: 30, size: 'A3' });
        let filename = 'Sales_Report.pdf';
        res.setHeader('Content-Disposition', 'attachment; filename=' + filename);
        res.setHeader('Content-Type', 'application/pdf');

        doc.fontSize(26).fillColor('#2c3e50').text('Company Sales Report', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(14).fillColor('gray').text('Generated by Aranoz on: ' + new Date().toLocaleDateString(), { align: 'center' });
        doc.moveDown(2);

        const tableTop = 150;
        const columnWidths = {
            date: 70,
            productName: 150,
            quantity: 80,
            billingName: 150,
            totalPrice: 100,
            discountPrice: 100,
            paymentMethod: 120
        };

        const xOffsets = {
            date: 30,
            productName: 30 + columnWidths.date,
            quantity: 30 + columnWidths.date + columnWidths.productName,
            billingName: 30 + columnWidths.date + columnWidths.productName + columnWidths.quantity,
            totalPrice: 30 + columnWidths.date + columnWidths.productName + columnWidths.quantity + columnWidths.billingName,
            discountPrice: 30 + columnWidths.date + columnWidths.productName + columnWidths.quantity + columnWidths.billingName + columnWidths.totalPrice,
            paymentMethod: 30 + columnWidths.date + columnWidths.productName + columnWidths.quantity + columnWidths.billingName + columnWidths.totalPrice + columnWidths.discountPrice
        };

        doc.fontSize(10).fillColor('white').rect(30, tableTop, xOffsets.paymentMethod + columnWidths.paymentMethod - 30, 20).fill('#2c3e50').stroke();
        
        doc.fillColor('white')
            .text('Date', xOffsets.date, tableTop + 5)
            // .text('Product Name', xOffsets.productName, tableTop + 5)
            .text('Quantity', xOffsets.quantity, tableTop + 5)
            .text('Billing Name', xOffsets.billingName, tableTop + 5)
            .text('Total Price', xOffsets.totalPrice, tableTop + 5)
            .text('Discount Price', xOffsets.discountPrice, tableTop + 5)
            .text('Payment Method', xOffsets.paymentMethod, tableTop + 5);

        let currentTop = tableTop + 20;
        const itemsPerPage = 20;
        let totalSalesAmount = 0;

        SalesReport.forEach((sale, i) => {
            if (i % 2 === 0) {
                doc.fillColor('#f8f9fa').rect(30, currentTop, xOffsets.paymentMethod + columnWidths.paymentMethod - 30, 20).fill().stroke();
            } else {
                doc.fillColor('white').rect(30, currentTop, xOffsets.paymentMethod + columnWidths.paymentMethod - 30, 20).fill().stroke();
            }

            doc.fillColor('black')
                .text(new Date(sale.orderDate).toLocaleDateString(), xOffsets.date, currentTop + 5)
                .text(sale.product.productname || 'N/A', xOffsets.productName, currentTop + 5)
                .text(sale.products.productquantity || 0, xOffsets.quantity, currentTop + 5)
                // .text(sale.user.name || 'Unknown', xOffsets.billingName, currentTop + 5)
                .text(`₹${sale.totalAmount ? sale.totalAmount.toFixed(2) : '0.00'}`, xOffsets.totalPrice, currentTop + 5)
                .text(`₹${sale.discountAmount ? sale.discountAmount.toFixed(2) : '0.00'}`, xOffsets.discountPrice, currentTop + 5)
                .text(sale.selectedPaymentMethod || 'N/A', xOffsets.paymentMethod, currentTop + 5);

            totalSalesAmount += sale.totalAmount || 0;

            currentTop += 20;

            if (i > 0 && i % itemsPerPage === 0) {
                doc.addPage();
                currentTop = tableTop + 20;

                doc.fontSize(10).fillColor('white').rect(30, tableTop, xOffsets.paymentMethod + columnWidths.paymentMethod - 30, 20).fill('#2c3e50').stroke();
                doc.fillColor('white')
                    .text('Date', xOffsets.date, tableTop + 5)
                    .text('Product Name', xOffsets.productName, tableTop + 5)
                    .text('Quantity', xOffsets.quantity, tableTop + 5)
                    // .text('Billing Name', xOffsets.billingName, tableTop + 5)
                    .text('Total Price', xOffsets.totalPrice, tableTop + 5)
                    .text('Discount Price', xOffsets.discountPrice, tableTop + 5)
                    .text('Payment Method', xOffsets.paymentMethod, tableTop + 5);
            }
        });

        doc.moveDown(2);
        doc.fontSize(12).fillColor('black').text(`Total Sales Amount: ₹${totalSalesAmount.toFixed(2)}`, { align: 'center' }, xOffsets.totalPrice, currentTop);


        doc.pipe(res);
        doc.end();
    } catch (error) {
        console.error("Error generating PDF:", error);
        res.status(500).send('Server error');
    }
};

    
const downloadExcel = async (req, res) => {
    try {
        const { startDate, endDate } = req.query;

        let query = { 'products.orderStatus': 'Delivered' };

        if (startDate && endDate) {
            const start = new Date(startDate);
            const end = new Date(endDate);
            end.setHours(23, 59, 59, 999);

            query.orderDate = {
                $gte: start,
                $lte: end
            };
        }

        let SalesReport = await order.aggregate([
            {
                $lookup: {
                  from: "addresses", 
                  localField: 'addressId',
                  foreignField: '_id',
                  as: 'address' 
                }
              },
              { $unwind: '$address' },
            { $unwind: '$products' },
            {
                $lookup: {
                    from: "products",
                    localField: 'products.productId',
                    foreignField: '_id',
                    as: 'product'
                }
            },
            { $unwind: '$product' },
            { $match: query },
            { $sort: { 'orderDate': -1 } },
            {
                $project: {
                    _id: 1,
                    orderDate: 1,
                    'product.productname': 1,
                    'products.productquantity': 1,
                    'user.name': 1,
                    totalAmount: 1,
                    discountAmount: 1,
                    selectedPaymentMethod: 1  
                }
            }
        ]);

        // Create an Excel workbook and worksheet
        const workbook = new ExcelJS.Workbook();
        const worksheet = workbook.addWorksheet('Sales Report');

        // Define columns for the Excel file
        worksheet.columns = [
            { header: 'Date', key: 'date', width: 15 },
            { header: 'Product Name', key: 'productName', width: 30 },
            { header: 'Quantity', key: 'quantity', width: 10 },
            // { header: 'Billing Name', key: 'billingName', width: 25 },
            { header: 'Total Price', key: 'totalPrice', width: 15 },
            { header: 'Discount Price', key: 'discountPrice', width: 15 },
            { header: 'Payment Method', key: 'paymentMethod', width: 20 }
        ];

        let totalSalesAmount = 0;

        // Process each sale in the SalesReport
        SalesReport.forEach(sale => {
            const totalPrice = sale.totalAmount || 0;
            const discountPrice = sale.discountAmount || 0;

            totalSalesAmount += totalPrice;

            // Add row to the worksheet
            worksheet.addRow({
                date: new Date(sale.orderDate).toLocaleDateString(),
                productName: sale.product.productname || 'N/A',
                quantity: sale.products.productquantity || 0,
                // billingName: sale.user.name || 'Unknown',
                totalPrice: `₹${totalPrice.toFixed(2)}`,
                discountPrice: `₹${discountPrice.toFixed(2)}`,
                paymentMethod: sale.selectedPaymentMethod || 'N/A'
            });
        });

     
        worksheet.addRow({
            date: 'Total',
            productName: '',
            quantity: '',
            // billingName: '',
            totalPrice: `₹${totalSalesAmount.toFixed(2)}`,
            discountPrice: '',
            paymentMethod: ''
        });

        // Set response headers for file download
        res.setHeader('Content-Disposition', 'attachment; filename=Sales_Report.xlsx');
        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

        // Write to the response
        await workbook.xlsx.write(res);
        res.end();
    } catch (error) {
        console.error("Error generating Excel file:", error);
        res.status(500).send('Server error');
    }
};


const loadWallet = async (req, res) => {
    try {
        const userId = req.session.user;
        const wallet = await Wallet.findOne({ userId });

        if (!wallet) {
            return res.status(404).json({ message: 'Wallet not found' });
        }

        // Pagination variables
        const page = parseInt(req.query.page) || 1; 
        const limit = 5; 
        const startIndex = (page - 1) * limit; 
        const endIndex = page * limit; 

       
        const transactions = wallet.history.slice(startIndex, endIndex);
        
        // Calculate total pages
        const totalPages = Math.ceil(wallet.history.length / limit);
        
        res.render('user/Wallet', {
            wallet: wallet,
            user: req.session.user,
            transactions: transactions, // Pass the sliced transactions
            currentPage: page,
            totalPages: totalPages,
        });
    } catch (error) {
        console.log(error);
        res.status(500).send('Internal Server Error');
    }
};







//getwalletDetails
const getWalletDetails = async (req, res) => {
    try {
        const userId = req.session.user; 
        const wallet = await Wallet.findOne({ userId });

        if (!wallet) {
            return res.status(404).json({ message: 'Wallet not found' });
        }

        res.json(wallet);
    } catch (error) {
        console.error('Error fetching wallet details:', error);
        res.status(500).json({ message: 'Error fetching wallet details', error });
    }
};

// const getTransactionHistory = async (req, res) => {
//     try {
//         const userId = req.session.user; 
//         const wallet = await Wallet.findOne({ userId });

//         if (!wallet) {
//             return res.status(404).json({ message: 'Wallet not found' });
//         }

//         res.status(200).json(wallet.history);
//     } catch (error) {
//         console.error('Error fetching transaction history:', error);
//         res.status(500).json({ message: 'Error fetching transaction history', error });
//     }
// };

// const addFunds = async (req, res) => {
//     try {
//         const userId = req.session.user; 
//         const { amount } = req.body;

//         if (amount <= 0) {
//             return res.status(400).json({ message: 'Invalid amount' });
//         }

//         let wallet = await Wallet.findOne({ userId });

//         if (!wallet) {
//             wallet = new Wallet({ userId, balance: 0, history: [] });
//         }

//         wallet.balance += amount;
//         wallet.history.push({
//             date: new Date(),
//             amount,
//             transactionType: 'credit',
//             newBalance: wallet.balance,
//             description: 'Funds added',
//         });

//         await wallet.save();

//         res.status(200).json({ message: 'Funds added successfully', wallet });
//     } catch (error) {
//         console.error('Error adding funds:', error);
//         res.status(500).json({ message: 'Error adding funds', error });
//     }
// };

// const withdrawFunds = async (req, res) => {
//     try {
//         const userId = req.session.user; 
//         const { amount } = req.body;

//         if (amount <= 0) {
//             return res.status(400).json({ message: 'Invalid amount' });
//         }

//         let wallet = await Wallet.findOne({ userId });

//         if (!wallet || wallet.balance < amount) {
//             return res.status(400).json({ message: 'Insufficient balance' });
//         }

//         wallet.balance -= amount;
//         wallet.history.push({
//             date: new Date(),
//             amount,
//             transactionType: 'debit',
//             newBalance: wallet.balance,
//             description: 'Funds withdrawn',
//         });

//         await wallet.save();

//         res.status(200).json({ message: 'Funds withdrawn successfully', wallet });
//     } catch (error) {
//         console.error('Error withdrawing funds:', error);
//         res.status(500).json({ message: 'Error withdrawing funds', error });
//     }
// };


//loadOrderDetails page
const loadOrderDetails = async (req, res) => {
    try {
        // Ensure that req.params.id is a valid ObjectId
        const orderId = req.params.id;

        const orders = await order.findById(orderId)
            .populate('userId')
            .populate('addressId')
            .populate('products.productId');

        if (!order) {
            return res.status(404).json({ message: 'Order not found' });
        }

        res.render('admin/orderDetails', { orders });
    } catch (error) {
        console.log('Error:', error);
        res.status(500).render('500', { message: 'Internal Server Error' });
    }
};




module.exports = {
    loadSalesReport,
    downloadPdf,
    downloadExcel,
    loadWallet,
    getWalletDetails,
    // getTransactionHistory,
    // addFunds,
    // withdrawFunds,
    loadOrderDetails,
};
